# Generated by Django 5.1.7 on 2025-03-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMePage',
            new_name='AboutMePost',
        ),
        migrations.AlterModelOptions(
            name='aboutmepost',
            options={'verbose_name_plural': 'Acerca de mí'},
        ),
    ]
