# Generated by Django 5.1.7 on 2025-04-08 17:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_rename_aboutmepage_aboutmepost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmepost',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
