# Generated by Django 5.1.7 on 2025-03-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tag',
            field=models.CharField(choices=[('PR', 'Personal'), ('CD', 'Código')], default='CD', max_length=2),
        ),
    ]
