# Generated by Django 5.1.7 on 2025-03-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tag',
            field=models.CharField(choices=[('NT', 'Notas'), ('LR', 'Aprendiendo')], default='LR', max_length=2),
        ),
    ]
