# Generated by Django 5.1.7 on 2025-03-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_entry_slug_alter_entry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
