# Generated by Django 5.1.7 on 2025-04-08 17:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_entry_slug_alter_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
