# Generated by Django 5.1.7 on 2025-05-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_alter_entry_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="slug",
            field=models.SlugField(editable=False, max_length=100),
        ),
    ]
